// PLACES ACTIONS
export const SET_PLACE = 'SET_PLACE';
export const FIND_PLACES = 'FIND_PLACES';
export const QUERY_CHANGED = 'QUERY_CHANGED';
export const UPDATE_CURRENT_LOCATION = 'UPDATE_CURRENT_LOCATION';
export const LOADING_DETAILS = 'LOADING_DETAILS';
export const LIKE_COMMENT = 'LIKE_COMMENT';
export const LIKE_COMMENT_ERROR = 'LIKE_COMMENT_ERROR';

// USERS ACTIONS
export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR'
export const SIGN_IN = "SIGN_IN";
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
export const SIGN_OUT = 'SIGN_OUT';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';